### PR TITLE
Fix label size and offset to top

### PR DESCRIPTION
**Pull request by tszkanlo**
Fix Label size cannot show the whole text and add offset to top.

### CODE REVIEW

**Comment by LawrenceHan** [comment]
Could you tell me what is this for?
Also could you write some test code inside SVViewController so that I can test with it?
Once I tested your changes and there's no bug, then I will merge your code.
@tszkanlo Thank you in advance.

P.S: Currently, we are using `SVPullToRefreshView` as refresh title, if you haven't checkout this part of code, you can pull the latest changes from my branch and see the different.

### Line 28 - 31 in `SVViewController.m`

```
    // setup pull-to-refresh
    [self.tableView addPullToRefresh:[SVDemoPullToRefresh class] withActionHandler:^{
        [weakSelf insertRowAtTop];
    }];
```

**Comment by laoyur** [comment]
@tszkanlo Good!
@LawrenceHan I can confirm this PR works.
the original code can only show a limited length of title, eg:
`Loading` will show as something like `Loa...`

**Comment by LawrenceHan** [comment]
@laoyur OK then, let me double check it.

**Comment by LawrenceHan** [comment]
@tszkanlo @laoyur Sorry for late reply, I was so busy. I tested with iPhone 5c and under iOS 8.1.2.
It seems works well with latest changes. Also I updated demo project settings.

**Pull request merged**
