### PR TITLE
Update UIScrollView+SVInfiniteScrolling.m

### PR DESCRIPTION
**Pull request by LawrenceHan**
Fix bug for re-initializing infinite scrollview

### CODE REVIEW

**Comment by LawrenceHan** [comment]
@soelynn What's this for?

**Comment by realsoelynn** [comment]
I encountered into a scenario where the UIView is reused and it wasn't bind correctly.
Otherwise, it will cause the program to crash.

**Comment by LawrenceHan** [comment]
@soelynn This is make sense to me, so I will merge it after you answered my question.
Have you tested it in other scenario? Is it works well?

**Comment by realsoelynn** [comment]
Yes, I did and this solved that.

**Comment by LawrenceHan** [comment]
@soelynn Thank you for your contribution.

**Pull request merged**
